export const negotiationStatusOrder = [
  // "Deal Started",
  "Paid",
  "Actively Negotiating",
  "Paid Holding",
  "Delivery Scheduled",
  "Shipping",
  "Deal Complete- Long Distance", //"Deal Complete - Long Term Order",
  "Needs To Review",
  "Long Term Order ", // this has a space at the end in db :/, a bit annoying
  "Ask for Review",
];

export const negotiationMakeColors: Record<string, string> = {
  Acura: "#d1e2ff",
  "Alfa Romeo": "#c4ecff",
  "Aston Martin": "#c1f5f0",
  Audi: "#cff5d1",
  Bentley: "#ffeab6",
  BMW: "#ffe0cc",
  Buick: "#d1e2ff",
  Cadillac: "#39caff",
  Chevrolet: "#e0dafd",
  Chrysler: "#e5e9f0",
  Dodge: "#a0c6ff",
  Ferrari: "#88dbff",
  Fiat: "#74ebe1",
  Ford: "#9ae095",
  Genesis: "#c4ecff",
  GMC: "#ffd66b",
  Honda: "#ffb68e",
  Hummer: "#ffa6c1",
  Hyundai: "#f797ef",
  Infiniti: "#d1e2ff",
  Jaguar: "#c4c7cd",
  Jeep: "#166ee1",
  Kia: "#39caff",
  Lamborghini: "#01ddd5", // Fixed typo in name
  "Land Rover": "#048a0e",
  Lexus: "#ffba05",
  Lincoln: "#d6404",
  Lotus: "#dc073d",
  Maserati: "#dd04a8",
  Mazda: "#7c37ef",
  "Mercedes-Benz": "#616670",
  Mini: "#0d52ac",
  Mitsubishi: "#0f68a2",
  Nissan: "#17726e",
  Porsche: "#006400",
  Ram: "#af6002",
  Rivian: "#ffd4e0",
  Subaru: "#aa2d00",
  Tesla: "#b10f41",
  Toyota: "#ab0a83",
  Volkswagen: "#6231ae",
  Volvo: "#41454d",
};
