export const DEFAULT_SORTED_COLUMN = "brand";

export const negotiationStatusOrder = [
  // "Deal Started",
  // "Paid",
  // "Actively Negotiating",
  // "Paid Holding",
  // "Deal Complete- Local",
  // "Shipping",
  // "Deal Complete- Long Distance", //"Deal Complete - Long Term Order",
  // "Needs To Review",
  // "Long Term Order", // this has a space at the end in db :/, a bit annoying
  // "Ask for Review",

  "Paid",
  "Paid Holding",
  "Deal Started",
  "Actively Negotiating",
  "Deal Complete- Local",
  "Deal Complete- Long Distance",
  "Long Term Order",
  "Shipping",
  "Needs To Review",
  "Ask for Review",
  "Closed",
  "Closed No Review",
  "Follow Up",
  "Follow Up Issue",
  "Paid Lost Contact",
  "Contacted",
  "Unqualified",
  "Lost",
  "No Show",
  "Canceled",
  // for consult mode
  // "Refunded",
  // "Scheduled",
  // "Proposal Sent",
];

export const statusColors: Record<string, string> = {
  Paid: "#d4fce2",
  "Paid Holding": "#a77af9",
  "Deal Started": "#d5c8fc",
  "Actively Negotiating": "#d3fccc",
  "Deal Complete- Local": "#59bd4f",
  "Deal Complete- Long Distance": "#0e4c0e",
  "Long Term Order": "#f8dce8",
  Shipping: "#fca7c4",
  "Needs To Review": "#f7c5f3",
  "Ask for Review": "#c5ebf7",
  Closed: "#f5bc5e",
  "Closed No Review": "#d94d26",
  "Follow Up": "#9ef6f6",
  "Follow Up Issue": "#54e2e2",
  "Paid Lost Contact": "#00c8c8",
  Refunded: "#d476e5",
  Contacted: "#d5c8fc",
  Scheduled: "#c5ebf7",
  "Proposal Sent": "#f7c5f3",
  Unqualified: "#d3d3d3",
  Lost: "#f24822",
  "No Show": "#d3d3d3",
  Canceled: "#f8dce8",
};

export const negotiationMakeColors: Record<string, string> = {
  Acura: "#d1e2ff",
  "Alfa Romeo": "#c4ecff",
  "Aston Martin": "#c1f5f0",
  Audi: "#cff5d1",
  Bentley: "#ffeab6",
  BMW: "#ffe0cc",
  Buick: "#d1e2ff",
  Cadillac: "#39caff",
  Chevrolet: "#e0dafd",
  Chrysler: "#e5e9f0",
  Dodge: "#a0c6ff",
  Ferrari: "#88dbff",
  Fiat: "#74ebe1",
  Ford: "#9ae095",
  Genesis: "#c4ecff",
  GMC: "#ffd66b",
  Honda: "#ffb68e",
  Hummer: "#ffa6c1",
  Hyundai: "#f797ef",
  Infiniti: "#d1e2ff",
  Jaguar: "#c4c7cd",
  Jeep: "#166ee1",
  Kia: "#39caff",
  Lamborghini: "#01ddd5", // Fixed typo in name
  "Land Rover": "#048a0e",
  Lexus: "#ffba05",
  Lincoln: "#d64040",
  Lotus: "#dc073d",
  Maserati: "#dd04a8",
  Mazda: "#7c37ef",
  "Mercedes-Benz": "#616670",
  Mini: "#0d52ac",
  Mitsubishi: "#0f68a2",
  Nissan: "#17726e",
  Porsche: "#006400",
  Ram: "#af6002",
  Rivian: "#ffd4e0",
  Subaru: "#aa2d00",
  Tesla: "#b10f41",
  Toyota: "#ab0a83",
  Volkswagen: "#6231ae",
  Volvo: "#41454d",
};
