import { z } from "zod";

/**
 
got user: {
  trim_and_package_options: [],
  invoice_status: [],
  name: 'Troy Paul',
  privilege: 'Team',
  payment_type: [],
  color_options: [],
  deal_closed_date: [],
  deal_started_date: [],
  id: 'recu1VwBaNVQAh236',
  is_onboarding_complete: [],
  deal_created_time: [],
  drive_train: '\n',
  profile_pic: null,
  consult_date: [],
  model: [],
  source: 'airtable',
  negotiation_id: [],
  deal_coordinator_id: 'recvufOWlPDZRq6O3',
  phone: null,
  role: [ 'Deal Coordinator Lead ' ],
  brand: [],
  email: 'tpaul@delivrdto.me',
  active_deals: [
    'reczbJGmhO7gY7irv', 'recGlWRzXZnDlIh0G', 'recDlgBUN0USSge22',
    'recLo4legKJfYPme9', 'recoBOa2tGgthmVQu', 'recpgYkQN1aUSUUzJ',
    'rec3oXnHVVReDRSo0', 'rec2Sxw96cGydTXVD', 'recYsTGanBwCiUQdJ',
    'recVHkurEHQ9LsEPR', 'recXBMSrN6SePAxT2', 'recNNxnxeLBzd9okh',
    'rec0UMscEMX1PKw5O', 'recaQPfEMjuLhC18U', 'rec3bHxfr7LCtkyaM',
    'recH7ijMu1Qi8aRF4', 'recDF7pEOueEg0yOw', 'recSA9B7IgOmXLsLm',
    'recHaQwHv9Bdit8Pj', 'recu2HrLCVROOEKM1', 'recizzBMy3DxWwIGd',
    'recZvRiIMkdQKWXJI', 'rec4KyvHqo3t8sDFF', 'recbAGLI0SkOBdUvd',
    'recqiIaAo7Et7a6in', 'reczO4rVrKJJT5pQn', 'recn9s8lVPNNgqS6M',
    'recKxOAibGUOeZFQI', 'reciMOZizKPTQCH0a', 'rectbAX5rno6TIdT1',
    'rechtRrQmqmRXDSeM', 'recwdWBuVOiOszKqj', 'recxPbcdIUKdj7Hi6',
    'recypd4AqnSMu1aDa', 'recKWenq3BhTO3sPb', 'recNwRLDaTUit6cdz',
    'recypsr3NXAAkogH3', 'recqiPy7UDMY71ksw', 'recLGl5oQFcQLk5Qy',
    'recjttIHLZTjEc8CL', 'recs383U0Q7o4kb7l', 'rec9xojZRnQg8fHUZ',
    'recZwPxWyTEyFehVH', 'recVohkFfYf5ErZOl', 'recpHX7NmFEb5MLSG',
    'rec0lYu9jBWreUswW', 'recqvV70FptEzo9Xs', 'recwrHPv7QgjEVbHt',
    'recVJ64y56rawf5S7', 'recmtDlK8k4Fvziui', 'recwd082nUDZEhES7',
    'recRs0gekW92dPRyl', 'recUpCvbKAAqsdWGF', 'rec5YcZDPbJVS2tYg',
    'recSI9V5l40H9mXvz', 'recYFLQWg2dBrh5s3', 'recesTcAKQCvbUWN1',
    'rec5k9U5qKObw4wM8', 'recB8CjXQY9VZCkx3', 'recqd4UCgiC1hMDaT',
    'recir967abx2fIfPx', 'recEolwYg9cnByei4', 'rec9QoUGEL31siDJ5',
    'rec8qaS4Ig6pkpaf3', 'recKMvPzvG7OKlIKw', 'reciavRoHwE2fKo7O',
    'recv43FUP5NLoeU5B', 'recS0bNxsmAcVQvo9', 'recchvnwJrj5s9GZG',
    'recz4jhZBlZidziCB', 'recRSZ7HmygqZWkzA'
  ],
  deal_negotiator: [],
  revenue: 0,
  dealer_id: [],
  trade_details: [],
  video_link: [ 'https://vimeo.com/1022159406/95339cb02b?share=copy' ]
}
 */

export const UserModel = z.object({
  id: z.string(),
  name: z.string(),
  email: z.string().email(),
  profile_pic: z.string().nullable(),
  role: z.string().nullable(),
  video_link: z.string().nullable(),
  source: z.string(),
  privilege: z.string().optional(),
  active_deals: z.array(z.string()).default([]),
  deals: z.array(z.string()).default([]),
  deal_negotiator: z.array(z.string()).default([]),
  trim_and_package_options: z.array(z.string()).default([]),
  invoice_status: z.array(z.string()).default([]),
  payment_type: z.array(z.string()).default([]),
  color_options: z.array(z.string()).default([]),
  deal_closed_date: z.array(z.string()).default([]),
  deal_started_date: z.array(z.string()).default([]),
  is_onboarding_complete: z.array(z.string()).default([]),
  deal_created_time: z.array(z.string()).default([]),
  drive_train: z.string().default(""),
  negotiation_id: z.array(z.string()).default([]),
  deal_coordinator_id: z.string().default(""),
  phone: z.string().nullable(),
  brand: z.array(z.string()).default([]),
  model: z.array(z.string()).default([]),
  consult_date: z.array(z.string()).default([]),
  revenue: z.number().default(0),
  dealer_id: z.array(z.string()).default([]),
  trade_details: z.array(z.string()).default([]),
  mode: z.string().optional(),
});

export type UserType = z.infer<typeof UserModel>;
